name: Publish to GitHub Package Registry

on:
  push:
    branches:
      - master

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@kevinegstorf'
          
      - run: npm run test
      
      - name: Setup GIT
        run: |
          git switch -c master
          git config --global user.email "kevin.egstorf@gmail.com"
          git config --global user.name "kevinegstorf"
          
      - name: Bump version
        run: |
          npm version patch
          git push https://${{secrets.GPR_TOKEN}}@github.com/PeterHewat/test-actions-gpr
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        
    
        

