
name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Setup GIT
        run: |
          git switch -c master
          git config --global user.email "kevin.egstorf@gmail.com"
          git config --global user.name "kevinegstorf"
      - run: npm ci
      - run: | 
          npm version patch
          git push https://${{secrets.GH_Token}}@github.com/kevinegstorf/zilver-ui/blob/master/package.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
